### ISSUE TITLE
Support Firefox based browser

### ISSUE THREAD

**Issue by lamyergeier** [balta2ar/brotab#118]
I installed **brotab** on a firefox based browser: [zen-browser/desktop](https://github.com/zen-browser/desktop).

But the `brotab clients` does not list the browser. Can you please support it?

**Comment by andreivolt** [comment]
you have to move the `brotab_mediator.json` file to wherever that browser stores them, on macOS it should be something like `~/Library/Application\ Support/.../NativeMessagingHosts`  and on Linux `~/.../native-messaging-hosts`
