### ISSUE TITLE
commands return nothing

### ISSUE THREAD

**Issue by oldwinterton** [balta2ar/brotab#13]
Dunno. did the pip. the install. added browser extensions. 
'bt {list,close...}' returns nothing.
'bt move' yields permission error. Would that permission error stop other elements of the program from functioning correctly? Or is something else afoot?

**Comment by balta2ar** [comment]
can you share the exact output after `bt move`? also, `/tmp/brotab.log` and `/tmp/brotab_mediator.log`.

**Comment by balta2ar** [comment]
You didn't specify which OS you're on. If you are on Windows, version 1.2.0 features much better support out of the box (but it may take weeks for the chrome extions to be reviewed and published). Anyway, try 1.2.0 now if you're on Firefox.
