### ISSUE TITLE
No such file or directory: 'C:\\tmp\\brotab.log'

### ISSUE THREAD

**Issue by Jalkhov** [balta2ar/brotab#14]
Good night, I have installed **brotab** through **pip** in **windows** and when writing **bt** in the **console** it throws me the error written above, what will be the problem?

**Comment by balta2ar** [comment]
I've never tested it on Windows and used paths that would only make sense for Linux. I'll see what I can do when I have time but to be honest, windows is not priority. Feel free to suggest a PR though.

Writing logs is one thing, and when it's fixed, the next problem that I expect is the manifest installation using bt install. That would require modifications for windows as well, I think.

**Comment by Jalkhov** [comment]
> 
> 
> I've never tested it on Windows and used paths that would only make sense for Linux. I'll see what I can do when I have time but to be honest, windows is not priority. Feel free to suggest a PR though.
> 
> Writing logs is one thing, and when it's fixed, the next problem that I expect is the manifest installation using bt install. That would require modifications for windows as well, I think.

Okay I understand, the truth is that the tools offered by the script call my attention and it would be great to be multiplatform, I think for now I will have to find an alternative, do you know any?

**Comment by balta2ar** [comment]
That's the problem: I created brotab because I couldn't find an alternative suitable for my needs.
