### ISSUE TITLE
No module named _internal.cli.main while trying to install brotab 

### ISSUE THREAD

**Issue by sladwig** [balta2ar/brotab#27]
Hi,

for me on a mac the installations via `pip install brotab` fails:

````
❯ pip install brotab
Traceback (most recent call last):
  File "/Users/esca/Library/Python/2.7/bin/pip", line 5, in <module>
    from pip._internal.cli.main import main
ImportError: No module named _internal.cli.main

❯ python --version
Python 2.7.10
````
I also tried python 3 before, which also failed but I don't have the error message at hand. (will add it if I find it).

Will try installing/using via git next.

**Comment by balta2ar** [comment]
Does it happen with other packages? The traceback shows no connection to `brotab` at all. I have no idea what I can do here. It may be something with your local pip/python setup. Another option is to install in a virtualenv/conda.

**Comment by sladwig** [comment]
so I found the `pip3` version and from what it looks like it was actually a problem with my internet connection dropping mi install and me not reading properly the error message before... will close the issue and thanks!
