### ISSUE TITLE
Xubuntu Bionic - brotab doesn't appear to be working correctly

### ISSUE THREAD

**Issue by zz0rk** [balta2ar/brotab#36]
FYI: I've brotab running on Ubuntu 20.04 with Chrome - no issues.
---
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
Chrome Version 83.0.4103.116 (Official Build) (64-bit)

pip3 install --user brotab AND sudo pip3 install brotab same results
bt installed with no issues; extension for Chrome installed with no issues.
When I execute 'bt client', 'bt list', 'bt windows', etc. not results are returned.

**Comment by balta2ar** [comment]
Did you install Chrome from snap package? If so, see this: https://github.com/balta2ar/brotab/issues/33

Otherwise more information needed, e.g. your logs `/tmp/brotab.log`, `/tmp/brotab_mediator.log`

**Comment by zz0rk** [comment]
Hi, Yuri: No, I don't use the snap package. So I went ahead uninstalled and re-installed and it appears to be working now. Sorry for the false positive. I hope this is going to be a permanent fix. : )

Cheers
