### ISSUE TITLE
[Feature request] Control tab sound

### ISSUE THREAD

**Issue by kamaradclimber** [balta2ar/brotab#51]
Hello,

I'd like to mute/unmute sound of a given tab programmatically. It would be very comfortable to be able to use brotab to do this.
Do you know if this could be done?

**Comment by kamaradclimber** [comment]
Looking at the code, one way to let users implement such mechanism would be to allow to execute a user script against a given tab.

Workflow could be then:
```
# to mute
bt query +audible | awk '{print $1}' | xargs -n1 -I{} bt run {} ./mute.js

# to unmute
bt query +muted | awk '{print $1}' | xargs -n1 -I{} bt run {} ./unmute.js
```

with (un)mute.js the exact piece of javascript taking a tab in input and muting it.

Of course such feature would allow the ability to inject code (but this extension is already doing this in a way)

**Comment by balta2ar** [comment]
Now in version 1.4.1 it's possible with `update` command:
```
bt query +muted | awk '{print $1}' | xargs -n1 -I{} bt update -tabId={} -muted
```

**Comment by kamaradclimber** [comment]
Thanks it works!
