### ISSUE TITLE
[feature request] pin and unpin tabs

### ISSUE THREAD

**Issue by bjohas** [balta2ar/brotab#58]
It would be nice if brotab (or the API) could pin/unpin tabs.

**Comment by balta2ar** [comment]
@bjohas  Yep, now it's possible. Similar to https://github.com/balta2ar/brotab/issues/51, but use `pinned`, e.g.:
```
bt query -url 'https://pin.com/*' | awk '{print $1}' | xargs -n1 -I{} bt update -tabId={} +pinned
```
