### ISSUE TITLE
brotab close

### ISSUE THREAD

**Issue by bjohas** [balta2ar/brotab#66]
On `brotab close b.14.20` I get
```
urllib.error.HTTPError: HTTP Error 500: INTERNAL SERVER ERROR
```
Closing the tab via curl works.

Might be related to https://github.com/balta2ar/brotab/issues/57.

**Comment by balta2ar** [comment]
yes, it's related to #57, I'm afraid error handling is not perfect... I'll close this one as duplicate, but feel free to report new cases if you find them.
