### ISSUE TITLE
404 and `bt active` vs `bt query +active`

### ISSUE THREAD

**Issue by bjohas** [balta2ar/brotab#70]
When I have 'stale' clients, I've noticed that
```
bt active
```
gives the 404 error, while 
```
bt query +active
```
works.

However, aren't those commands equivalent?

**Comment by balta2ar** [comment]
No, they use different API endpoints and show different output. However, I'd rather not focus on states where normal operation is not possible -- i.e. "stale" clients. If there's any action in this issue, then it's preventing the mediator to get into "stale" state in the first place -- not working around the consequences after getting there.

**Comment by bjohas** [comment]
Yes, makes sense!
