### ISSUE TITLE
Add instructions for installing with pipx

### ISSUE THREAD

**Issue by rsyring** [balta2ar/brotab#78]
Using [pipx](https://github.com/pypa/pipx) for cli applications has been a game changer for installing cli packages.  I'd like to suggest that you consider adding that as an installation option in the readme (and consider making it the recommended way).  IMO it's just as easy as `pip ... --user` but has the advantage of automatically getting it's own virtualenv.

**Comment by balta2ar** [comment]
Thanks for the tip!
