### ISSUE TITLE
Include source for package brotab.albert

### ISSUE THREAD

**Issue by rsyring** [balta2ar/brotab#79]
Would you include the `brotab/albert` directory when packing the source code?  Rational:

* I use pipx to install and update brotab
* I'd like to make `~/.local/share/albert/org.albert.extension.python/modules/brotab_search.py` a link to the pipx installed brotab
* Result: it's easy to keep the albert plugin up-to-date by updating brotab (`pipx update brotab`)

Thanks.

**Comment by rsyring** [comment]
Well, using pipx for this use case won't work as expected.  Albert's python need to be able to `import brotab`.  So I'll go back to a `pip ... --user`  install.  

It would still be nice to have the albert package included in the source.

**Comment by balta2ar** [comment]
Added :+1:  Will be part of a package starting from next release.
